apiVersion: v1
kind: Service
metadata:
  name: blogify-backend-service
  namespace: blogify-ns

spec:
  selector:
    app: blogify-backend

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  type: ClusterIP
