apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogify-frontend-deploy
  namespace: blogify-ns

spec:
  replicas: 1

  selector:
    matchLabels:
      app: blogify-frontend

  template:
    metadata:
      name: blogify-frontend
      labels:
        app: blogify-frontend

    spec:
      containers:
        - name: blogify-frontend-container
          image: yashkhakhkhar455/blogify-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
