apiVersion: v1
kind: Service
metadata:
  name: blogify-frontend-service
  namespace: blogify-ns

spec:
  selector:
    app: blogify-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP
