services:
  backend:
    image: yashkhakhkhar455/blogify-backend:v1
    container_name: blogify-backend
    expose:
      - "8080"
    environment:
      PORT: $PORT
      MONGO_URI: $MONGO_URI
      JWT_SECRET: $JWT_SECRET
      CLOUDINARY_CLOUD_NAME: $CLOUDINARY_CLOUD_NAME
      CLOUDINARY_API_KEY: $CLOUDINARY_API_KEY
      CLOUDINARY_API_SECRET: $CLOUDINARY_API_SECRET
    restart: always

  nginx:
    image: yashkhakhkhar455/blogify-frontend:v1
    container_name: blogify-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always