services:
  backend:
    image: yashkhakhkhar455/blogify-backend:v1
    container_name: blogify-backend
    expose:
      - "8080"
    env_file:
      - ../backend/.env
    restart: always

  nginx:
    image: yashkhakhkhar455/blogify-frontend:v1
    container_name: blogify-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always