services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.DockerFile
    image: blogify-backend
    container_name: blogify-backend
    expose:
      - "8080"

  nginx:
    build:
      context: ..
      dockerfile: docker/frontend.DockerFile
    image: blogify-frontend
    container_name: blogify-frontend
    ports:
      - "80:80"
    depends_on:
      - backend