name: Build and Deploy Blogify

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    # LOGIN DOCKER HUB
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    # ==============================
    # BUILD BACKEND IMAGE
    # ==============================
    - name: Build backend image
      run: |
        docker build --no-cache \
        -f docker/backend.DockerFile \
        -t yashkhakhkhar455/blogify-backend:v1 \
        .

    - name: Push backend image
      run: docker push yashkhakhkhar455/blogify-backend:v1


    # ==============================
    # BUILD FRONTEND IMAGE
    # ==============================
    - name: Build frontend image
      run: |
        docker build --no-cache \
        -f docker/frontend.DockerFile \
        -t yashkhakhkhar455/blogify-frontend:v1 \
        .

    - name: Push frontend image
      run: docker push yashkhakhkhar455/blogify-frontend:v1


    # ==============================
    # DEPLOY ON EC2
    # ==============================
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          echo "🚀 Deployment started"

          # CHANGE THIS if your repo is elsewhere on EC2
          APP_DIR="/home/ec2-user/projects/Blogify/docker"

          cd $APP_DIR

          echo "📥 Pulling latest images"
          docker pull yashkhakhkhar455/blogify-backend:v1
          docker pull yashkhakhkhar455/blogify-frontend:v1

          echo "🛑 Stopping old containers"
          docker compose down

          echo "📝 Creating .env file from GitHub secrets"
          
          cat > ../backend/.env <<EOF
          PORT=${{ secrets.PORT }}
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          EOF

          echo "▶️ Starting containers"
          docker compose up -d

          echo "✅ Deployment finished"
